version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: php_docker
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    links:
      - mysql
    environment:
      DB_HOST: mysql
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: app 
      MYSQL_USER: web_user
      MYSQL_PASSWORD: mypass
      MYSQL_ROOT_PASSWORD: root




